name: FastCoref
program: main.py
method: grid
parameters:
  data_dir:
    value: '/mnt/nfs/scratch1/sdhuliawala/dpr_sentence_splits_genre_tagged_final/'
  out_dir:
    value: '/mnt/nfs/scratch1/dthai/fast-coref/tagged_wiki/'
  filename:
    values: ['file_9-3-genre.jsonl', 'file_9-4-genre.jsonl', 'file_9-5-genre.jsonl', 'file_9-6-genre.jsonl', 'file_9-7-genre.jsonl', 'file_9-8-genre.jsonl', 'file_9-9-genre.jsonl']
  model_path:
    value: '/mnt/nfs/scratch1/dthai/fast-coref/'
  encoder_name:
    value: 'shtoshni/longformer_coreference_joint'
  use_wandb:
    value: 1
